from app.services.index_service import load_query_engine

engine = load_query_engine()
response = engine.query("What controls should govern consequential agent actions?")
print(response)
print(response.source_nodes)


"""
THIS FUNCTION GENERATED BY GEMINI to help me understand the output cleanly
"""
def print_clean_response(response):
    print("\n" + "="*50)
    print("🤖 AI SYNTHESIZED RESPONSE")
    print("="*50)
    print(response.response)
    
    print("\n" + "="*50)
    print("📄 SOURCE EVIDENCE TRAIL")
    print("="*50)
    
    for i, source in enumerate(response.source_nodes, 1):
        # Extract the fields safely
        score = source.score
        file_name = source.node.metadata.get("file_name", "Unknown")
        content = source.node.get_content()
        
        print(f"\n[{i}] Document: {file_name} | Match Score: {score:.4f}")
        print("-" * 40)
        print(content.strip())
        print("-" * 40)

print_clean_response(response)